name: Azure login
description: "Login to Azure & configure az CLI."
inputs:
  azure_credentials:
    description: "Credentials authorized to create Constellation on Azure."
    required: true
runs:
  using: "composite"
  steps:
    # As described at:
    # https://github.com/Azure/login#configure-deployment-credentials
    - name: Login to Azure
      uses: azure/login@7184910d9eb2b1c5e48f7073824a90609bb9b6d6 # v2.3.1
      with:
        creds: ${{ inputs.azure_credentials }}
